version: '3.6'
services:
  vault:
    image: hashicorp/vault
    container_name: vault-new-1
    environment:
      VAULT_ADDR: "http://localhost:8200"
      VAULT_API_ADDR: "http://localhost:8200"
      VAULT_ADDRESS: "http://localhost:8200"
    ports:
      - "18200:8200"
      - "18201:8201"
    restart: always
    volumes:
      - ./logs:/vault/logs/:rw
      - ./data:/vault/data/:rw
      - ./config:/vault/config/:rw
      - ./certs:/certs/:rw
      - ./file:/vault/file/:rw
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config /vault/config/config.hcl
    networks:
      - iris_vault_network

networks:
  iris_vault_network:
    driver: bridge
